#!/bin/sh


while read file
do
        case "$1" in
            "C-s")
                mv "$file" "~/core.d/wallpapers/$(ls ~/core.d/wallpapers/*/ -d | rofi -dmenu)"  ;;
            "C-r")
                convert -rotate 90 "$file" "$file" ;;
            "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done
