language: emacs-lisp

before_install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  - sudo add-apt-repository -yy ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
env:
  - EMACS=emacs25
install:
  - cask install
script:
  - emacs25 --version
  - cask emacs  -batch -l pri.el 
