#!/bin/sh

ws1="1: "
ws2="2: "
ws3="3: "
ws4="4: "
ws5="5: "
ws6="6: "
ws7="7: "


if [ ! $(emacsclient -e '(message "1")') ]; then
	# echo "yes"
	emacs --daemon
	# else
	# 	echo "no"
fi

i3-msg "workspace ${ws1}; exec /usr/bin/firefox"
sleep 1
i3-msg "workspace ${ws2}; exec emacsclient -c"
i3-msg "workspace ${ws3}; exec rxvt-unicode"
i3-msg "workspace ${ws4}; exec /usr/bin/firefox"
sleep 1
i3-msg "workspace ${ws5}; exec rxvt-unicode -e ranger"
i3-msg "workspace ${ws7}; exec spotify"

