#!/bin/bash



while getopts c:b:s: option
do
    case "${option}"
    in
        c)
            cp $2 "${WALLPAPER_DIR}/"
			wal  -i $2 -a 85;;
		b)
            cp $2 "${WALLPAPER_DIR}/"
            cp $2 ${WALLPAPER} && feh --bg-scale ${WALLPAPER} ;;
        s)
            PAPE=$(ls "${WALLPAPER_DIR}/"*.{jpg,png,bmp} | sxiv -tio)
            cp "${PAPE}" ${WALLPAPER} && feh --bg-scale ${WALLPAPER} ;;

    esac
done
