#!/bin/bash

DIR="$HOME/.scripts"


for point in $(cat $DIR/conf/mounts); do

	if [ -b "/dev/disk/by-label/$point" ] ; then
	    [ -d "$HOME/core.d/$point" ] || mkdir "$HOME/core.d/$point"
	    [ -e "/dev/disk/by-label/$point" ] && sudo mount "/dev/disk/by-label/$point"  "$HOME/core.d/$point"
	fi

done
