#!/bin/bash



while getopts c:b:s:r option
do
    case "${option}"
    in
        c)
            cp $2 "${WALLPAPER_DIR}/"
	    wal  -i $2 -a 85 -n;
            feh --no-fehbg --bg-scale $2;;
        
	b)
            cp $2 "${WALLPAPER_DIR}/"
            cp $2 ${WALLPAPER} && feh --no-fehbg --bg-scale ${WALLPAPER} ;;
        s)
            
            PAPE=$(ls "${WALLPAPER_DIR}/"*.{jpg,png,bmp} | sxiv -tio)
            cp "${PAPE}" ${WALLPAPER} && feh --no-fehbg --bg-scale ${WALLPAPER} ;;
        
        r)
            feh --no-fehbg --bg-scale ${WALLPAPER}
            ;;

    esac
done
