#!/bin/bash

ws1="1:  Laptop"
ws2="2:  Code"
ws3="3:  Terminal"
ws4="4:  Internet"
ws5="5:  Files"
ws6="6:  Documents"
ws7="7:  Media"
ws8="8:  Documents"
ws9="9:  Chat"
ws10="10:  General"

if [ $(emacsclient -e '(message "1")') != "\"1\"" ]; then
    emacs --daemon
fi

i3-msg "workspace ${ws1}; exec /usr/bin/firefox"
i3-msg "workspace ${ws2}; exec emacsclient -c"
i3-msg "workspace ${ws3}; exec rxvt-unicode; split h; exec rxvt-unicode;"
i3-msg "workspace ${ws4}; exec /usr/bin/firefox"
i3-msg "workspace ${ws5}; exec  exec rxvt-unicode -e ranger; split h ; nautilus"
i3-msg "workspace ${ws6}; exec evince"
i3-msg "workspace ${ws7}; exec spotify"

