#!/bin/sh



case $BLOCK_BUTTON in
    1) lmc toggle ;;
esac

STATUS=$(playerctl status)

echo $STATUS

if ! [ "$STATUS" == "No players found"]; then
	STATUS="Stopped"

fi


echo $STATUS



# if $STATUS
# then
# 	echo $STATUS
# else
# 	echo "Off"
# fi


