#!/bin/bash

case $BLOCK_BUTTON in
    1) pavucontrol ;;
    3) pamixer -t ;;
    4) pamixer -i 5 ;;
    5) pamixer -d 5 ;;
esac

printpastatus() { [[ $(/home/arnaud/core.d/code/pamixer/pamixer --get-mute) = "true" ]] && echo -n 🔇 && exit
                  echo 🔊 $(/home/arnaud/core.d/code/pamixer/pamixer --get-volume)% ;}
printpastatus
